import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/ui/NavBar/NavBar";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import MySession from "@/components/MySession/MySession";


const inter = Exo({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by Abdelrahman Ahmed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`antialiased`}
      >
        <MySession>

          <NavBar />
            <Toaster />
          {children}
        </MySession>
      </body>
    </html>
  );
}
